<?php
/**
 * @file catman_custom.module
 *
 * A module for Catman customizations
 *
 */


/**
 * Implements hook_commerce_line_item_summary_link_info_alter().
 */
function catman_custom_order_commerce_line_item_summary_link_info_alter(&$links) {
  // Link checkout button to the cart.
  if (isset($links['checkout'])) {
    $links['checkout']['href'] = 'cart';
  }
}

/**
 * Implements hook_views_api().
 */
function catman_custom_order_views_api() {
  return array(
    "version" => "3.0",
    'path' => drupal_get_path('module', 'catman_custom') . '/includes/views',
  );
}


/**
* Implements hook_node_view().
* don't display store data if add to store field is not checked
*/
function catman_custom_node_view($node, $view_mode, $langcode) { 

  if ($node->field_add_to_store['und'][0]['value'] == 0) {
    unset($node->field_publication_product);
  }

}


/**
* Implements hook_form_alter().
*/
function catman_custom_form_alter(&$form, &$form_state, $form_id) {

  switch ($form_id) {

    case 'osu_catalog_publication_node_form':

      $form['field_supplemental_file']['und'][0]['#description'] = t('');

    break;

    case 'commerce_checkout_form_review':
    
      global $user;

      if (in_array('OSU affiliate', array_values($user->roles)) || in_array('Reseller', array_values($user->roles)) || in_array('PNW', array_values($user->roles)) ) { 
        $form['commerce_payment']['payment_method']['#options']['commerce_purchase_order|commerce_payment_commerce_purchase_order'] = t('Purchase order or OSU index');
        $form['commerce_payment']['payment_details']['po_number']['#title'] = t('PO or index number');
      }

    break;
  }

}

/**
 * Implements hook_block_info().
 */
function catman_custom_block_info() {
  $blocks = array(
    'eesc_invoice_header' => array(
      'info' => t('EESC header information for invoices'),
    ),
    'eesc_invoice_footer' => array(
      'info' => t('EESC footer information for invoices'),
    ),
  );
 
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function catman_custom_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'eesc_invoice_header':

      $block['content'] = t('
        <div class="catman-invoice-header">
          <div><strong>Extension and Experiment Station Communications</strong></div>
          <div>Oregon State University<br />
            422 Kerr Administration Bldg.<br />
            Corvallis, OR 97331-2119<br />
            Phone: 541-737-2513 or 800-561-6719
          </div>
          <div>Email: puborders@oregonstate.edu</div>
          <div>http://extension.oregonstate.edu/catalog</div>
        </div>
        ');
      break;

    case 'eesc_invoice_footer':

      $block['content'] = t('
        <div class="catman-invoice-footer">
          <p>Thanks for your order!</p>

          <div><strong>If your invoice shows a balance:</strong><br />
          If you are paying with an OSU index, we will process a journal voucher to complete your payment.<br />
          If you are paying with a purchase order, payment is due upon receipt of your order. Please forward this invoice to your accounts payable department. Include the invoice or invoice number
          with your payment. Make checks payable to OSU and send to:</div>
          <div class="indent-payment">Extension and Experiment Station Communications, Oregon State University, 422 Kerr Administration Bldg., Corvallis, OR 97330-2119</div>
        </div>
        ');
      break;

  }
  return $block;
}





/**
 * Implements hook_commerce_payment_method_info().
 */
function catman_custom_commerce_payment_method_info_alter(&$payment_methods)  {
  $payment_methods = array();

  $payment_methods['commerce_purchase_order'] = array(
    'title' => t('Purchase Order or OSU Index'),
  );

  return $payment_methods;
}



