<?php
/**
 * @file catman_custom.module
 *
 * A module for Catman customizations
 *
 */


/**
 * Implements hook_commerce_line_item_summary_link_info_alter().
 */
function catman_custom_order_commerce_line_item_summary_link_info_alter(&$links) {
  // Link checkout button to the cart.
  if (isset($links['checkout'])) {
    $links['checkout']['href'] = 'cart';
  }
}

/**
 * Implements hook_views_api().
 */
function catman_custom_order_views_api() {
  return array(
    "version" => "3.0",
    'path' => drupal_get_path('module', 'catman_custom') . '/includes/views',
  );
}


/**
* Implements hook_node_view().
* don't display store data if add to store field is not checked
*/
function catman_custom_node_view($node, $view_mode, $langcode) { 

  if ($node->field_add_to_store['und'][0]['value'] == 0) {
    unset($node->field_publication_product);
  }

}


/**
* Implements hook_form_alter().
*/
function catman_custom_form_alter(&$form, &$form_state, $form_id) {

  switch ($form_id) {

    case 'osu_catalog_publication_node_form':
    //dpm($form);

    $form['field_supplemental_file']['und'][0]['#description'] = t('');

    break;

    case 'commerce_checkout_form_review':
    //dpm($form);

    $form['commerce_payment']['payment_method']['#options']['commerce_purchase_order|commerce_payment_commerce_purchase_order'] = t('Purchase order or OSU index');
    $form['commerce_payment']['payment_details']['po_number']['#title'] = t('PO or index number');

    break;
  }

}

/**
 * Ajax callback for subaccount input in beauty07ajax_form form.
 */
// function publication_product_callback($form, $form_state) {

//   // if ($form_state['field']['field_add_to_store']['und']['field']['columns']['value'] = NOT_NULL) {
//   //   $form_state['field']['field_publication_product']['#access'] = TRUE;
//   // }
//   // else {
//   //   $form_state['field']['field_publication_product']['#access'] = FALSE;
//   // }

//   // if ($form_state['field']['field_add_to_store']['und']['field']['columns']['value']['not null']) {
//   //   $form_state['field_publication_product']['#access'] = TRUE;
//   //   $form_state['inline_entity_form']['#access'] = TRUE;
//   // }
//   // else {
//   //   $form_state['field_publication_product']['#access'] = FALSE;
//   //   //$form_state['inline_entity_form']['#access'] = FALSE;
//   // }

//   return $form['osu_catalog_publication_node_form'];
// }

